'use strict';
const $=id=>document.getElementById(id);
const parts=[
{id:'solar',group:'Energie & Wasser',name:'Solarzelle',icon:'☀',x:35,y:174,w:162,h:104},
{id:'water',group:'Energie & Wasser',name:'Wasserbehälter',icon:'◒',x:215,y:98,w:90,h:85},
{id:'ec',group:'Elektrolyseur',name:'Kathode (−)',note:'Elektrode mit Katalysator',icon:'−',x:282,y:310,w:50,h:160},
{id:'em',group:'Elektrolyseur',name:'PEM-Membran',icon:'▥',x:336,y:310,w:42,h:160},
{id:'ea',group:'Elektrolyseur',name:'Anode (+)',note:'Elektrode mit Katalysator',icon:'+',x:382,y:310,w:50,h:160},
{id:'th',group:'Elektrolyseur',name:'Gasspeicher H₂',icon:'H₂',x:455,y:90,w:84,h:155},
{id:'to',group:'Elektrolyseur',name:'Gasspeicher O₂',icon:'O₂',x:562,y:90,w:84,h:155},
{id:'fa',group:'Brennstoffzelle',name:'Anode (−)',note:'Elektrode mit Katalysator',icon:'−',x:664,y:310,w:50,h:160},
{id:'fm',group:'Brennstoffzelle',name:'PEM-Membran',icon:'▥',x:718,y:310,w:42,h:160},
{id:'fc',group:'Brennstoffzelle',name:'Kathode (+)',note:'Elektrode mit Katalysator',icon:'+',x:764,y:310,w:50,h:160},
{id:'motor',group:'Verbraucher',name:'Motor mit Propeller',icon:'✣',x:860,y:350,w:100,h:104}];
parts.push({id:'ch',name:'Auffangbehälter A',x:460,y:315,w:72,h:110},{id:'co',name:'Auffangbehälter B',x:565,y:315,w:72,h:110});
const ports=[
{id:'sminus',part:'solar',x:55,y:284,type:'electric',color:'#24374b',label:'Solarzelle −'},
{id:'splus',part:'solar',x:176,y:284,type:'electric',color:'#b54443',label:'Solarzelle +'},
{id:'wout',part:'water',x:306,y:155,type:'water',color:'#148974',label:'Wasserbehälter Ausgang'},
{id:'ewater',part:'ea',x:434,y:335,type:'water',color:'#148974',label:'Elektrolyseur Wasserzufuhr'},
{id:'eminus',part:'ec',x:305,y:480,type:'electric',color:'#24374b',label:'Elektrolyseur Kathode −'},
{id:'eplus',part:'ea',x:405,y:480,type:'electric',color:'#b54443',label:'Elektrolyseur Anode +'},
{id:'eh',part:'ec',x:305,y:296,type:'gas',color:'#147ca8',label:'Elektrolyseur Gasausgang Kathode'},
{id:'eo',part:'ea',x:405,y:296,type:'gas',color:'#147ca8',label:'Elektrolyseur Gasausgang Anode'},
{id:'thin',part:'th',x:475,y:253,type:'gas',color:'#147ca8',label:'H₂-Speicher Eingang'},
{id:'thout',part:'th',x:519,y:253,type:'gas',color:'#147ca8',label:'H₂-Speicher Ausgang'},
{id:'toin',part:'to',x:581,y:253,type:'gas',color:'#147ca8',label:'O₂-Speicher Eingang'},
{id:'toout',part:'to',x:627,y:253,type:'gas',color:'#147ca8',label:'O₂-Speicher Ausgang'},
{id:'fh',part:'fa',x:685,y:296,type:'gas',color:'#147ca8',label:'Wasserstoffgaseinleitung der Brennstoffzelle'},
{id:'fo',part:'fc',x:785,y:296,type:'gas',color:'#147ca8',label:'Sauerstoffgaseinleitung der Brennstoffzelle'},
{id:'fminus',part:'fa',x:685,y:480,type:'electric',color:'#24374b',label:'Brennstoffzelle Anode −'},
{id:'fplus',part:'fc',x:785,y:480,type:'electric',color:'#b54443',label:'Brennstoffzelle Kathode +'},
{id:'mminus',part:'motor',x:890,y:465,type:'electric',color:'#24374b',label:'Motor −'},
{id:'mplus',part:'motor',x:934,y:465,type:'electric',color:'#b54443',label:'Motor +'}];
ports.push({id:'chin',part:'ch',x:478,y:437,type:'gas',color:'#147ca8',label:'Auffangbehälter A Eingang'},{id:'chout',part:'ch',x:515,y:302,type:'gas',color:'#147ca8',label:'Auffangbehälter A Ausgang'},{id:'coin',part:'co',x:582,y:437,type:'gas',color:'#147ca8',label:'Auffangbehälter B Eingang'},{id:'coout',part:'co',x:622,y:302,type:'gas',color:'#147ca8',label:'Auffangbehälter B Ausgang'});
const initial=()=>({placed:new Set(['solar','th','to','motor']),assembled:{e:false,f:false},drafts:{},hof:{valves:[false,false],levels:[0,0],air:[true,true],gas:[0,0],types:['',''],fluid:'',filled:false,escaped:0},selected:null,port:null,wires:[],tab:'build',running:false,h2:0,o2:0,water:100,product:0,light:100,angle:0,motor:true,producing:false,spinning:false,power:0,rotor:0});
let state=initial(),last=performance.now(),hintIndex=0,feedbackKey='';
function say(message,tone=''){ $('feedback').textContent=message;$('feedback').className='feedback '+tone;}
function has(a,b){return state.wires.some(w=>w.includes(a)&&w.includes(b));}
function installed(...ids){return ids.every(id=>state.placed.has(id));}
function collectionPath(source,target){return (has(source,'chin')&&has('chout',target))||(has(source,'coin')&&has('coout',target));}
function electroReady(){return state.assembled.e&&has('sminus','eminus')&&has('splus','eplus')&&has('wout','ewater')&&collectionPath('eh','thin')&&collectionPath('eo','toin');}
function gasReady(){return installed('fa','fm','fc','th','to')&&has('thout','fh')&&has('toout','fo');}
function motorReady(){return installed('motor')&&((has('fminus','mminus')&&has('fplus','mplus'))||(has('fminus','mplus')&&has('fplus','mminus')));}
function renderParts(){ $('parts').innerHTML=['e','f'].map(d=>`<button class="part" data-device="${d}"><span>${d==='e'?'Hofmann-Apparat':'PEM-Brennstoffzelle'}<small>${state.assembled[d]?'montiert · erneut öffnen':'Montage öffnen'}</small></span></button>`).join('');}
function selectPart(id){if(state.placed.has(id)){say('Dieses Teil ist bereits eingesetzt. Ein eingesetztes Bauteil auf der Werkbank anklicken, um es herauszunehmen.');return;}state.selected=id;renderParts();say(`${parts.find(p=>p.id===id).name} ausgewählt. Wähle einen passenden Platz auf der Werkbank.`);}
function place(target){if(state.tab!=='build')return;const p=parts.find(p=>p.id===target);if(state.placed.has(target)){state.placed.delete(target);state.wires=state.wires.filter(w=>!w.some(id=>ports.find(q=>q.id===id).part===target));state.running=false;state.producing=false;state.spinning=false;state.selected=target;render();say(`${p.name} herausgenommen. Zugehörige Leitungen wurden entfernt.`);return;}if(!state.selected){say('Wähle zuerst ein Bauteil aus der Liste.');return;}if(state.selected!==target){say('Dieses Bauteil passt nicht in diesen Platz. Überlege, zu welchem Gerät es gehört und welche Funktion es hat.','warn');return;}state.placed.add(target);state.selected=null;render();if(state.placed.size===parts.length)say('Alle Bauteile sind eingesetzt. Verbinde jetzt Kabel und Schläuche.','good');else say(`${p.name} eingesetzt.`,'good');}
function selectPort(id){if(state.tab!=='connect')return;const p=ports.find(p=>p.id===id);if(!state.port){state.port=id;renderBench();say(`${p.label} ausgewählt. Wähle den zweiten Anschluss.`);return;}if(state.port===id){state.port=null;renderBench();say('Auswahl aufgehoben.');return;}const a=ports.find(p=>p.id===state.port);if(a.type!==p.type){say('Die Anschlüsse passen nicht zusammen: Kabel verbinden elektrische Anschlüsse, Schläuche verbinden Gas- oder Wasseranschlüsse.','warn');return;}if(a.part===p.part){say('Verbinde Anschlüsse verschiedener Bauteile.','warn');return;}if(state.wires.some(w=>w.includes(a.id)||w.includes(p.id))){state.port=null;renderBench();say('Ein Anschluss ist schon belegt. Entferne zuerst die vorhandene Leitung durch Anklicken.','warn');return;}state.wires.push([a.id,p.id]);state.port=null;renderBench();updateReadouts();say('Leitung verbunden. Mit „Aufbau prüfen“ kannst du die Funktion überprüfen.');}
function diagnose(){if(!state.assembled.e||!state.assembled.f)return 'Die beiden Geräte müssen zuerst vollständig montiert und geprüft werden.';if(state.wires.length<8)return 'Der äußere Aufbau ist noch nicht vollständig. Prüfe, ob alle benötigten Anschlüsse verbunden sind.';if(!electroReady())return 'Der Elektrolyseur und seine Auffang- und Speicherwege sind noch nicht funktionsfähig. Überprüfe deinen Aufbau.';if(!gasReady()||!motorReady())return 'Die Brennstoffzelle und der Motor bilden noch keine funktionsfähige Anlage. Überprüfe deinen Aufbau.';return null;}
const rect=(x,y,w,h,fill,stroke='#b8cddc',r=8)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}" fill="${fill}" stroke="${stroke}"/>`;
const txt=(x,y,t,size=14,fill='#173248',anchor='middle',weight=400)=>`<text class="bench-text" x="${x}" y="${y}" text-anchor="${anchor}" style="font-size:${size}px;fill:${fill};font-weight:${weight}">${t}</text>`;
function partArt(p){const {x,y,w,h,id}=p;if(!state.placed.has(id)){let lines=id==='solar'?['Solarzelle']:id==='water'?['Wasser']:id==='motor'?['Motor']:id==='th'?['H₂']:id==='to'?['O₂']:id.endsWith('m')?['Membran']:['Elektrode'];return `<rect class="target" x="${x}" y="${y}" width="${w}" height="${h}" rx="8"/>${lines.map((l,i)=>id==='em'||id==='fm'?`<text x="${x+w/2}" y="${y+h/2}" text-anchor="middle" class="slot-label" transform="rotate(-90 ${x+w/2} ${y+h/2})">${l}</text>`:txt(x+w/2,y+h/2+5+i*16,l,14,'#658297')).join('')}`;}
if(id==='solar'){let cells='';for(let row=0;row<4;row++)for(let col=0;col<6;col++)cells+=rect(x+10+col*24,y+9+row*21,21,18,'#23628c','#75a8cb',2);return rect(x,y,w,h,'url(#panel)','#244f6e')+cells+txt(x+20,y+h+22,'−',18)+txt(x+w-20,y+h+22,'+',18,'#b54443');}
if(id==='water')return rect(x,y,w,h,'#ffffffb3','#89b1c8')+rect(x+4,y+26,w-8,h-30,'#b2e1f3','none',5)+txt(x+w/2,y+20,'H₂O',18)+txt(x+w/2,y+h-10,`${Math.round(state.water)} %`,14,'#346a87');
if(id==='ch'||id==='co')return rect(x,y,w,h,'#ffffffbd','#94b4c9',12)+rect(x+5,y+30,w-10,h-35,'#dbeef7','none',6)+txt(x+w/2,y+24,id==='ch'?'A':'B',19)+txt(x+w/2,y+h+30,'Auffang',12,'#55758b');
if(id==='th'||id==='to'){const vol=id==='th'?state.h2:state.o2,cap=id==='th'?120:60,color=id==='th'?'#4da7d2':'#df9386',height=vol/cap*113;let ticks='';for(let i=1;i<6;i++)ticks+=`<path d="M${x+7} ${y+28+i*20} h12" stroke="#9bb8ca"/>`;return rect(x,y,w,h,'#ffffffc9','#8aaec6',12)+rect(x+4,y+27,w-8,124,'#dbeef7','none',8)+rect(x+4,y+27,w-8,height,color,'none',6)+ticks+txt(x+w/2,y+21,id==='th'?'H₂':'O₂',18,id==='th'?'#12688e':'#a55142','middle',700)+txt(x+w/2,y+h-10,'IN · OUT',12,'#55758b')+txt(x+w/2,y+44,`${cap} mL max.`,12,'#385a71');}
if(id==='motor'){return rect(x+18,y+8,64,87,'url(#metal)','#87a6bc',12)+`<circle cx="910" cy="400" r="38" fill="#edf5fa" stroke="#92b2c8"/><g transform="rotate(${state.rotor} 910 400)"><path d="M910 400 C879 370 894 356 907 366 C919 375 917 389 910 400 M910 400 C948 388 951 408 936 414 C923 419 917 410 910 400 M910 400 C902 438 883 430 888 415 C892 402 902 398 910 400" fill="#177bb2"/><circle cx="910" cy="400" r="8" fill="#173248"/></g>`;}
if(id==='em'||id==='fm')return rect(x,y,w,h,'url(#membrane)','#bc9b37',5)+`<text x="${x+w/2}" y="${y+h/2}" text-anchor="middle" transform="rotate(-90 ${x+w/2} ${y+h/2})" style="font-size:14px;fill:#725717">PEM · H⁺</text>`;
const cathode=id==='ec'||id==='fc',minus=id==='ec'||id==='fa';return rect(x,y,w,h,'url(#electrode)','#8fa8ba',6)+rect(x+8,y+8,7,h-16,cathode?'#197eab':'#b76a56','none',2)+txt(x+w/2+3,y+32,minus?'−':'+',24,minus?'#173248':'#ae4e43','middle',700)+`<text x="${x+w/2+3}" y="${y+h/2+20}" text-anchor="middle" transform="rotate(-90 ${x+w/2+3} ${y+h/2+20})" style="font-size:14px;fill:#fff">${cathode?'Kathode':'Anode'}</text>`;
}
function trackFlow(a,b){if(!state.flowWires)state.flowWires=new Set();state.flowWires.add([a,b].sort().join('|'));}
function isWireFlowing(w){if(!state.running)return false;const key=[...w].sort().join('|');if(w.includes('eh')||w.includes('eo')){const side=w.includes('eh')?0:1;return state.hof.valves[side]&&!!state.flowWires?.has(key);}if(w.some(id=>['thout','toout','fh','fo','fminus','fplus'].includes(id)))return state.spinning&&!!state.flowWires?.has(key);if(w.some(id=>['sminus','splus'].includes(id)))return state.producing;return false;}
function wireArt(w,i){const a=ports.find(p=>p.id===w[0]),b=ports.find(p=>p.id===w[1]);let d;const bothBottom=a.y>=465&&b.y>=465;const solar=(a.part==='solar'||b.part==='solar');if(bothBottom){const base=510+(i%2)*18;d=`M${a.x} ${a.y} V${base} H${b.x} V${b.y}`;}else if(solar){const base=505+(i%2)*18;d=`M${a.x} ${a.y} V${base} H${b.x} V${b.y}`;}else {const mid=(a.y+b.y)/2+(i%2)*9;d=`M${a.x} ${a.y} V${mid} H${b.x} V${b.y}`;}if(a.type==='gas'){const endpoint=ports.find(q=>q.id===w[0]);const other=ports.find(q=>q.id===w[1]);const collector=[endpoint,other].find(q=>q.part==='ch'||q.part==='co');if(collector){const o=collector===endpoint?other:endpoint;if(collector.id.endsWith('in')){const lane=collector.part==='ch'?456:448;d=`M${o.x} ${o.y} V${lane} H${collector.x} V${collector.y}`;}else{const lane=collector.part==='ch'?262:270;d=`M${collector.x} ${collector.y} V${lane} H${o.x} V${o.y}`;}}else{const lane=w.includes('thout')?280:287;d=`M${a.x} ${a.y} V${lane} H${b.x} V${b.y}`;}}if(w.includes('eh')&&w.includes('thin'))d='M306 209V180H440V264H475V253';if(w.includes('eo')&&w.includes('toin'))d='M406 209V190H550V274H581V253';if(w.some(id=>['fminus','fplus'].includes(id))&&w.some(id=>['mminus','mplus'].includes(id)))d=`M${a.x} ${a.y} V250 H${b.x} V${b.y}`;const color=a.type==='water'?'#168976':a.type==='gas'?(w.some(id=>['eo','toin','toout','fo'].includes(id))?'#b76a56':'#177eae'):a.color;const moving=isWireFlowing(w);return `<g class="wire" data-wire="${i}" tabindex="${state.tab==='connect'?0:-1}" role="button" aria-label="Leitung ${a.label} zu ${b.label} entfernen"><path d="${d}" stroke="transparent" stroke-width="18" fill="none"/><path d="${d}" stroke="${color}" stroke-width="5" stroke-linejoin="round" fill="none"/>${moving?`<path class="flow" d="${d}" stroke="#ffffffbd" stroke-width="2" fill="none"/>`:''}</g>`;}
function renderBench(){const solarLevel=state.light/100;let bubbles='';if(state.producing)for(const x of [307,407])for(let k=0;k<3;k++)bubbles+=`<circle class="bubble" cx="${x}" cy="430" r="${x===307?4:3}" fill="#bbe9fa" style="animation-delay:${k*.55}s"/>`;
$('bench').innerHTML=`<svg viewBox="0 0 1000 565" role="group" aria-label="Bauteile, Anschlüsse und Leitungen der Wasserstoffanlage"><defs><linearGradient id="panel" x2="1" y2="1"><stop stop-color="#184264"/><stop offset="1" stop-color="#327cad"/></linearGradient><linearGradient id="metal"><stop stop-color="#9db5c5"/><stop offset=".4" stop-color="#e0eaf0"/><stop offset="1" stop-color="#a6bdcd"/></linearGradient><linearGradient id="electrode"><stop stop-color="#5a6c79"/><stop offset=".5" stop-color="#788c9b"/><stop offset="1" stop-color="#455c6e"/></linearGradient><pattern id="membrane" width="7" height="7" patternUnits="userSpaceOnUse"><rect width="7" height="7" fill="#f3dfa1"/><path d="M0 0V7" stroke="#e6c866" stroke-width="2"/></pattern><pattern id="grid" width="25" height="25" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".8" fill="#c0d6e3"/></pattern></defs><rect width="1000" height="565" fill="url(#grid)" opacity=".45"/>
<path d="M20 545H980" stroke="#c9dfe9" stroke-width="2"/>
<g opacity="${.25+solarLevel*.75}"><circle cx="110" cy="84" r="25" fill="#f2c755"/>${Array.from({length:8},(_,i)=>{const a=i*Math.PI/4;return `<path d="M${110+Math.cos(a)*34} ${84+Math.sin(a)*34} L${110+Math.cos(a)*44} ${84+Math.sin(a)*44}" stroke="#e6b742" stroke-width="3" stroke-linecap="round"/>`;}).join('')}<path d="M86 130L74 160 M111 134L111 162 M136 130L147 160" stroke="#ebc657" stroke-width="3"/></g>
${txt(116,322,'Solarzelle',16,'#173248','middle',600)}${txt(550,60,'Getrennte Gasspeicher',16,'#173248','middle',600)}
${rect(645,286,186,208,'#eaf1f68a','#c0d3df',12)}
${txt(356,550,'Hofmann-Apparat',17,'#173248','middle',600)}${txt(738,550,'PEM-Brennstoffzelle',17,'#173248','middle',600)}${txt(910,335,'Motor',16,'#173248','middle',600)}
${state.wires.map(wireArt).join('')}
${['e','f'].filter(d=>!state.assembled[d]).map(d=>`<g data-device="${d}" tabindex="0" role="button" aria-label="${d==='e'?'Hofmann-Apparat':'PEM-Brennstoffzelle'} montieren" class="slot">${rect(d==='e'?263:645,300,186,188,'#f7fbfd','#91acbf',12)}${txt(d==='e'?356:738,378,'Montage öffnen',17)}${txt(d==='e'?356:738,406,'Einzelteile zusammensetzen',12,'#5a788d')}</g>`).join('')}
${parts.filter(p=>!['water','ch','co','ec','em','ea'].includes(p.id)).filter(p=>!['ec','em','ea'].includes(p.id)||state.assembled.e).filter(p=>!['fa','fm','fc'].includes(p.id)||state.assembled.f).map(p=>`<g class="component" data-slot="${p.id}" tabindex="-1" role="img" aria-label="${p.name}"><title>${p.name}</title>${partArt(p)}</g>`).join('')}

${ports.filter(p=>state.placed.has(p.part)&&!['wout','ewater','chin','chout','coin','coout'].includes(p.id)).map(p=>`<g class="port ${state.port===p.id?'selected':''}" data-port="${p.id}" role="button" tabindex="${state.tab==='connect'?0:-1}" aria-label="${p.label}"><title>${p.label}</title><circle class="hit" cx="${p.x}" cy="${p.y}" r="17"/><circle class="dot" cx="${p.x}" cy="${p.y}" r="7" fill="${p.color}" stroke="white" stroke-width="2"/></g>`).join('')}

</svg>`;
}
function updateReadouts(){ $('count').textContent=`${Number(state.assembled.e)+Number(state.assembled.f)} / 2`;$('progressFill').style.width=`${(Number(state.assembled.e)+Number(state.assembled.f))*50}%`;$('connectionCount').textContent=`${state.wires.length} Leitungen`;$('h2value').innerHTML=`${state.h2.toFixed(1).replace('.',',')} <small>mL</small>`;$('o2value').innerHTML=`${state.o2.toFixed(1).replace('.',',')} <small>mL</small>`;$('motorValue').textContent=state.spinning?'läuft':'steht';$('powerValue').innerHTML=`${Math.round(state.power)} <small>%</small>`;$('start').textContent=state.running?'Versuch pausieren':'Versuch starten';}
function render(){renderParts();renderBench();updateReadouts();}
function switchTab(tab){state.tab=tab;state.port=null;state.selected=null;state.running=false;state.producing=false;state.spinning=false;feedbackKey='';for(const t of document.querySelectorAll('[data-tab]')){t.classList.toggle('active',t.dataset.tab===tab);t.setAttribute('aria-pressed',String(t.dataset.tab===tab));}for(const t of ['build','connect','run'])$(t+'Tools').hidden=t!==tab;$('observations').hidden=tab!=='run';$('benchTitle').textContent=tab==='build'?'Werkbank · Bauteile einsetzen':tab==='connect'?'Werkbank · Anschlüsse verbinden':'Werkbank · Anlage betreiben';$('hintText').hidden=true;hintIndex=0;render();say(tab==='build'?'Öffne ein Gerät und montiere seine Einzelteile auf der freien Montagefläche.':tab==='connect'?'Wähle zwei Anschlüsse, um ein Kabel oder einen Schlauch zu verbinden.':'Starte den Versuch. Du kannst die Anlage auch mit unvollständigen Verbindungen untersuchen.');}
function step(dt){state.power=state.placed.has('solar')?state.light*Math.cos(state.angle*Math.PI/180):0;const rate=2*state.power/100;state.producing=state.running&&electroReady()&&state.water>0&&state.h2<119.999&&state.o2<59.999&&state.power>.01;
if(state.producing){const made=Math.max(0,Math.min(rate*dt,(120-state.h2)/2,60-state.o2,state.water/.04));state.h2+=2*made;state.o2+=made;state.water=Math.max(0,state.water-made*.04);}
state.spinning=state.running&&state.motor&&gasReady()&&motorReady()&&state.h2>.002&&state.o2>.001;
if(state.spinning){state.rotor=(state.rotor+(has('fminus','mplus')?-1:1)*dt*260)%360;const used=Math.min(.65*dt,state.h2/2,state.o2);state.h2=Math.max(0,state.h2-2*used);state.o2=Math.max(0,state.o2-used);state.product+=used*.0015;}
if(state.running){let message,tone='';const err=diagnose();if(state.spinning&&state.power<.01){message='Der Motor läuft mit dem gespeicherten Wasserstoff und Sauerstoff weiter. Ohne Licht entstehen keine neuen Gase.';tone='good';}else if(state.spinning&&state.producing){message='Gase entstehen und treiben den Motor an. Beide Speicher werden im Verhältnis 2 : 1 gefüllt und entleert.';tone='good';}else if(state.spinning){message='Der Motor läuft mit den gespeicherten Gasen. Im Elektrolyseur entstehen gerade keine neuen Gase.';tone='good';}else if(err){message=err;tone='warn';}else if(state.water<=0){message='Der Wasserbehälter ist leer. Fülle Wasser nach, um weitere Gase zu erzeugen.';tone='warn';}else if(state.h2>=119.99||state.o2>=59.99){message='Die Gasspeicher sind voll. Die Elektrolyse pausiert. Schließe den Motorstromkreis, um gespeicherte Gase zu nutzen.';}else if(state.producing&&!state.motor){message='Die Gasspeicher füllen sich. Bei geöffnetem Motorstromkreis werden keine Gase in der Brennstoffzelle umgesetzt.';tone='good';}else if(state.power<.01){message='Die Solarzelle liefert keine Leistung. Ohne gespeicherte Gase steht der Motor.';}else if(!state.motor){message='Der Motorstromkreis ist geöffnet. Der Motor steht.';}else {message='Die Gasspeicher sind leer. Warte, bis der Elektrolyseur Gas erzeugt.';}if(message!==feedbackKey){say(message,tone);feedbackKey=message;}}
updateReadouts();renderBench();}
$('parts').addEventListener('click',e=>{const b=e.target.closest('[data-device]');if(b)openAssembly(b.dataset.device);});
$('parts').addEventListener('dragstart',e=>{const b=e.target.closest('[data-part]');if(!b||state.placed.has(b.dataset.part)){e.preventDefault();return;}selectPart(b.dataset.part);e.dataTransfer.setData('text/plain',b.dataset.part);});
$('bench').addEventListener('dragover',e=>{if(state.tab==='build')e.preventDefault();});
$('bench').addEventListener('drop',e=>{e.preventDefault();const slot=e.target.closest('[data-slot]');if(slot)place(slot.dataset.slot);});
function benchAction(e){const device=e.target.closest('[data-device]');if(device){openAssembly(device.dataset.device);return;}const port=e.target.closest('[data-port]'),wire=e.target.closest('[data-wire]'),slot=e.target.closest('[data-slot]');if(port&&state.tab==='connect')selectPort(port.dataset.port);else if(wire&&state.tab==='connect'){state.wires.splice(Number(wire.dataset.wire),1);state.port=null;renderBench();updateReadouts();say('Leitung entfernt.');}}
$('bench').addEventListener('click',benchAction);$('bench').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();benchAction(e);}});
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
$('check').addEventListener('click',()=>{const err=diagnose();if(!err)document.querySelector('.knowledge').hidden=false;say(err||'Der Aufbau ist vollständig und funktionsfähig. Wechsle zu „Experimentieren“.',err?'warn':'good');});
$('start').addEventListener('click',()=>{state.running=!state.running;feedbackKey='';if(!state.running){state.producing=false;state.spinning=false;say('Versuch pausiert. Die gespeicherten Gase bleiben erhalten.');}step(0);});
$('light').addEventListener('input',e=>{state.light=Number(e.target.value);$('lightValue').textContent=`${state.light} %`;step(0);});
$('angle').addEventListener('input',e=>{state.angle=Number(e.target.value);$('angleValue').textContent=`${state.angle}°`;step(0);});
$('motorSwitch').addEventListener('change',e=>{state.motor=e.target.checked;step(0);});
$('refill').addEventListener('click',()=>openAssembly('e'));
$('drain').addEventListener('click',()=>{state.h2=state.o2=0;state.spinning=false;feedbackKey='';render();say('Beide Gasspeicher sind geleert.');});
$('reset').addEventListener('click',()=>{state=initial();resetGeometry();document.querySelector('.knowledge').hidden=true;$('light').value=100;$('angle').value=0;$('lightValue').textContent='100 %';$('angleValue').textContent='0°';$('motorSwitch').checked=true;switchTab('build');say('Die Werkbank ist zurückgesetzt. Öffne eines der beiden Geräte.');});
$('hint').addEventListener('click',()=>{const hints=state.tab==='build'?['Welche Funktion hat jedes Bauteil? Ordne erst Trennung, Reaktion und Speicherung zu.','Prüfe, welche Teile sich berühren dürfen und welche getrennt bleiben müssen.','Verfolge gedanklich den Weg von Wasser und Gasen durch deinen Aufbau.']:state.tab==='connect'?['Unterscheide elektrische Anschlüsse und Stoffleitungen, bevor du Verbindungen setzt.','Leite die Zuordnung der Pole aus der jeweiligen Elektrodenreaktion ab.','Prüfe für jeden Schlauch: Welcher Stoff verlässt den Ausgang, und welcher wird am Eingang benötigt?','Kontrolliere, ob die elektrischen Verbindungen einen vollständigen Stromkreis bilden.']:['Verändere nur eine Bedingung und beobachte ihre Wirkung.','Vergleiche den Betrieb mit und ohne Beleuchtung nach einer Phase der Gasgewinnung.','Stelle die Reaktionsgleichung auf und vergleiche die Koeffizienten mit deinen beobachteten Gasvolumina.'];$('hintText').hidden=false;$('hintText').textContent=hints[hintIndex++%hints.length];});
render();setInterval(()=>{const now=performance.now(),dt=Math.min((now-last)/1000,.5);last=now;if(state.running)step(dt);},180);

