'use strict';
const geometry={parts:parts.map(p=>({id:p.id,x:p.x,y:p.y})),ports:ports.map(p=>({id:p.id,x:p.x,y:p.y}))};
function resetGeometry(){for(const p of parts)Object.assign(p,geometry.parts.find(q=>q.id===p.id));for(const p of ports)Object.assign(p,geometry.ports.find(q=>q.id===p.id));}
parts.find(p=>p.id==='fa').name='Anoden-Platin-Elektrode';parts.find(p=>p.id==='fc').name='Kathoden-Platin-Elektrode';
const montage=document.createElement('dialog');montage.id='montage';montage.setAttribute('aria-labelledby','montageTitle');document.body.append(montage);
let activeDevice=null,drag=null,returnFocus=null;
const motorPins=[{id:'mminus',x:420,y:95,label:'−'},{id:'mplus',x:480,y:95,label:'+'}];
function draft(){return state.drafts.f;}
function newDraft(){return {layers:[{id:'a',kind:'electrode',label:'Anoden-Platin-Elektrode',x:75,y:80,w:96,h:180},{id:'mem',kind:'membrane',label:'PEM-Membran',x:470,y:65,w:44,h:180},{id:'b',kind:'electrode',label:'Kathoden-Platin-Elektrode',x:680,y:75,w:96,h:180},{id:'hi',kind:'inlet hydrogen',label:'Wasserstoffgaseinleitung',x:260,y:320,w:100,h:80},{id:'oi',kind:'inlet oxygen',label:'Sauerstoffgaseinleitung',x:485,y:330,w:100,h:80},{id:'wo',kind:'water-outlet',label:'Wasserauslass',x:690,y:325,w:100,h:80}],cables:[{id:'c1',ends:[{x:85,y:490},{x:250,y:530}]},{id:'c2',ends:[{x:420,y:485},{x:600,y:530}]}]};}
function openAssembly(device){if(device==='e'){openHofmann();return;}state.running=false;state.producing=false;state.spinning=false;render();returnFocus=document.activeElement;activeDevice='f';if(!state.drafts.f)state.drafts.f=newDraft();renderMontage();montage.showModal();}
function componentArt(p){if(p.kind==='electrode')return `<span class="layer-visual"><i class="catalyst"></i><span class="platinum-name">${p.id==='a'?'Anoden':'Kathoden'}<br>Platin-<br>Elektrode<br><b>Pt</b></span></span>`;if(p.kind==='membrane')return '<span class="layer-visual"><span>PEM</span></span>';
const right=accessoryRight(p),end=right?0:100,start=right?90:10;if(p.id==='wo')return `<svg viewBox="0 0 100 80" aria-hidden="true"><path d="M${end} 40H${start}" fill="none" stroke="#5897b8" stroke-width="7"/><rect x="${end-5}" y="32" width="10" height="16" fill="#5897b8"/>${txt(50,24,'H₂O',17)}</svg><span class="accessory-label">Wasserauslass</span>`;return `<svg viewBox="0 0 100 80" aria-hidden="true"><path d="M${start} 40H${end}" stroke="${p.id==='hi'?'#187eae':'#b86957'}" stroke-width="7"/><rect x="${end-5}" y="32" width="10" height="16" fill="${p.id==='hi'?'#187eae':'#b86957'}"/>${txt(50,24,p.id==='hi'?'H₂':'O₂',18)}</svg><span class="accessory-label">${p.id==='hi'?'Wasserstoff':'Sauerstoff'}<br>gaseinleitung</span>`;}
function cablePath(c){const [a,b]=c.ends,top=Math.max(20,Math.min(a.y,b.y)-35);return `M${a.x} ${a.y} V${top} H${b.x} V${b.y}`;}
function renderMontage(){const d=draft();montage.innerHTML=`<div class="montage-header"><div><p class="eyebrow">EINZELTEILE MONTIEREN</p><h2 id="montageTitle">PEM-Brennstoffzelle</h2></div><button id="closeMontage" class="quiet-button">Zur Gesamtanlage</button></div><p class="montage-instruction">Setze die Brennstoffzelle aus den Einzelteilen zusammen. Verbinde Gaseinleitungen, Wasserauslass und den Stromkreis über den Motor.</p><div class="montage-scroll"><div id="assemblyArea" aria-label="Freie Montagefläche"><svg class="fuel-cable-plane" viewBox="0 0 900 580" role="group" aria-label="Zwei Kabel mit beweglichen Enden und Motoranschlüsse"><g>${rect(395,50,115,92,'#e5f0f7','#9fbccc',10)}<circle cx="455" cy="95" r="26" fill="#f7fbfd" stroke="#91b2c8"/><path d="M455 75V115 M435 95H475" stroke="#177bb2" stroke-width="6"/>${txt(455,37,'Motor',15)}${motorPins.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="8" fill="#173248" stroke="white" stroke-width="2"/>${txt(p.x,p.y-18,p.label,18)}`).join('')}</g>${d.cables.map((c,i)=>`<g><path data-cable-path="${c.id}" d="${cablePath(c)}" stroke="${i===0?'#354b60':'#b34c42'}" stroke-width="5" fill="none"/>${c.ends.map((end,j)=>`<g data-cable-end="${c.id}:${j}" tabindex="0" role="button" aria-label="Kabel ${i+1}, Ende ${j+1}, mit Pfeiltasten verschieben"><circle class="cable-hit" cx="${end.x}" cy="${end.y}" r="17" fill="transparent"/><circle class="cable-dot" cx="${end.x}" cy="${end.y}" r="7" fill="${i===0?'#354b60':'#b34c42'}" stroke="white" stroke-width="2"/></g>`).join('')}</g>`).join('')}</svg>${d.layers.map(p=>`<button class="layer fuel-part ${p.kind}" data-layer="${p.id}" style="left:${p.x}px;top:${p.y}px;width:${p.w}px;height:${p.h}px" aria-label="${p.label}, mit Pfeiltasten verschieben">${componentArt(p)}</button>`).join('')}</div></div><div class="fuel-montage-footer"><p>Bauteile und Kabelenden frei verschieben: ziehen oder Pfeiltasten verwenden. Umschalt + Pfeiltaste bewegt sie weiter.</p><button class="primary" id="submitAssembly">Montage prüfen</button></div><p id="assemblyFeedback" class="assembly-feedback" role="status" aria-live="polite">Prüfe deinen Aufbau, wenn alle Teile verbunden sind.</p>`;updateAttachments();}
function corePorts(d){const a=d.layers.find(p=>p.id==='a'),b=d.layers.find(p=>p.id==='b'),left=a.x<b.x;return {aGas:{x:a.x+(left?-8:104),y:a.y+75},bGas:{x:b.x+(left?104:-8),y:b.y+75},water:{x:b.x+(left?104:-8),y:b.y+150},aElectric:{x:a.x+48,y:a.y-8},bElectric:{x:b.x+48,y:b.y-8}};}
function accessoryRight(p){const target=corePorts(draft())[p.id==='hi'?'aGas':p.id==='oi'?'bGas':'water'];return target.x>draft().layers.find(q=>q.id==='mem').x+22;}
function near(a,b){return Math.hypot(a.x-b.x,a.y-b.y)<=22;}
function connectionPoint(p){const right=accessoryRight(p);return {x:p.x+(right?0:100),y:p.y+40};}
function updateAttachments(){const d=draft();for(const p of d.layers.filter(p=>['hi','oi','wo'].includes(p.id)))montage.querySelector(`[data-layer="${p.id}"]`).innerHTML=componentArt(p);const targets=corePorts(d),svg=montage.querySelector('.fuel-cable-plane');svg.querySelector('[data-core-ports]')?.remove();const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('data-core-ports','');g.innerHTML=[targets.aGas,targets.bGas,targets.water].map(p=>`<rect x="${p.x-6}" y="${p.y-7}" width="12" height="14" rx="2" fill="#607f93"/>`).join('')+[targets.aElectric,targets.bElectric].map(p=>`<circle cx="${p.x}" cy="${p.y}" r="7" fill="#334f65" stroke="white" stroke-width="2"/>`).join('');svg.append(g);for(const c of d.cables){svg.querySelector(`[data-cable-path="${c.id}"]`).setAttribute('d',cablePath(c));for(let j=0;j<2;j++){const el=svg.querySelector(`[data-cable-end="${c.id}:${j}"]`);el.querySelectorAll('circle').forEach(circle=>{circle.setAttribute('cx',c.ends[j].x);circle.setAttribute('cy',c.ends[j].y);});svg.append(el);}}}
function assemblyValidation(d){const core=d.layers.filter(p=>['a','b','mem'].includes(p.id)).sort((a,b)=>a.x-b.x);if(core[1].id!=='mem'||Math.max(...core.map(p=>p.y))-Math.min(...core.map(p=>p.y))>26||core.slice(1).some((p,i)=>{const gap=p.x-(core[i].x+core[i].w);return gap< -12||gap>26;}))return {error:'Elektroden und Membran bilden noch keine funktionsfähige Zelle. Prüfe die Anordnung und die Abstände.'};const targets=corePorts(d),at=id=>connectionPoint(d.layers.find(p=>p.id===id));if(!near(at('hi'),targets.aGas)||!near(at('oi'),targets.bGas))return {error:'Die Gaseinleitungen sind noch nicht passend an die Zelle angeschlossen.'};if(!near(at('wo'),targets.water))return {error:'Die Wasserableitung ist noch nicht passend angeschlossen.'};const connected=[];for(const c of d.cables){let found=null;for(const [electrode,target]of [['a',targets.aElectric],['b',targets.bElectric]])for(const pin of motorPins){if((near(c.ends[0],target)&&near(c.ends[1],pin))||(near(c.ends[1],target)&&near(c.ends[0],pin)))found={electrode,pin:pin.id};}if(!found)return {error:'Die Kabel schließen noch keinen Stromkreis über beide Elektroden und den Motor.'};connected.push(found);}if(connected[0].electrode===connected[1].electrode||connected[0].pin===connected[1].pin)return {error:'Der Motorstromkreis ist noch nicht geschlossen. Prüfe beide Kabelenden.'};return {core,connected};}
function acceptAssembly(result){const ids=['fa','fm','fc'],left=result.core[0].id==='a';parts.find(p=>p.id==='fa').x=left?664:764;parts.find(p=>p.id==='fc').x=left?764:664;for(const p of ports.filter(p=>ids.includes(p.part))){const el=parts.find(q=>q.id===p.part);p.x=el.x+23;p.y=p.type==='electric'?296:370;if(p.type==='gas')p.x=el.x+(el.x===664?-8:58);}state.wires=state.wires.filter(w=>!w.some(id=>['fh','fo','fminus','fplus','mminus','mplus'].includes(id)));for(const c of result.connected)state.wires.push([c.electrode==='a'?'fminus':'fplus',c.pin]);ids.forEach(id=>state.placed.add(id));state.assembled.f=true;state.port=null;state.fAccessories=true;closeAssembly();render();say('Brennstoffzelle korrekt montiert. Die Motorkabel sind verbunden. Schließe nun die Gasspeicher an die Gaseinleitungen an.','good');}
function closeAssembly(){montage.close();activeDevice=null;drag=null;returnFocus?.focus();}
function areaPoint(e){const r=$('assemblyArea').getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
function moveItem(target,x,y){if(target.kind==='part'){const p=draft().layers.find(p=>p.id===target.id);p.x=Math.max(0,Math.min(900-p.w,x));p.y=Math.max(0,Math.min(580-p.h,y));const el=montage.querySelector(`[data-layer="${p.id}"]`);el.style.left=p.x+'px';el.style.top=p.y+'px';}else{const [id,i]=target.id.split(':'),p=draft().cables.find(c=>c.id===id).ends[Number(i)];p.x=Math.max(15,Math.min(885,x));p.y=Math.max(15,Math.min(555,y));}updateAttachments();}
function targetFrom(el){if(el.dataset.layer)return {kind:'part',id:el.dataset.layer};if(el.dataset.cableEnd)return {kind:'cable',id:el.dataset.cableEnd};return null;}
function itemPosition(target){if(target.kind==='part')return draft().layers.find(p=>p.id===target.id);const [id,i]=target.id.split(':');return draft().cables.find(c=>c.id===id).ends[Number(i)];}
montage.addEventListener('pointerdown',e=>{const el=e.target.closest('[data-layer],[data-cable-end]');if(!el)return;const target=targetFrom(el),p=itemPosition(target),point=areaPoint(e);drag={...target,dx:point.x-p.x,dy:point.y-p.y};el.setPointerCapture(e.pointerId);el.focus();e.preventDefault();});
montage.addEventListener('pointermove',e=>{if(!drag)return;const p=areaPoint(e);moveItem(drag,p.x-drag.dx,p.y-drag.dy);});montage.addEventListener('pointerup',()=>drag=null);montage.addEventListener('pointercancel',()=>drag=null);
montage.addEventListener('keydown',e=>{const el=e.target.closest('[data-layer],[data-cable-end]');if(!el||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const target=targetFrom(el),p=itemPosition(target),n=e.shiftKey?20:5;moveItem(target,p.x+(e.key==='ArrowRight'?n:e.key==='ArrowLeft'?-n:0),p.y+(e.key==='ArrowDown'?n:e.key==='ArrowUp'?-n:0));});
montage.addEventListener('click',e=>{if(e.target.id==='closeMontage')closeAssembly();if(e.target.id==='submitAssembly'){const result=assemblyValidation(draft());if(result.error){$('assemblyFeedback').textContent=result.error;$('assemblyFeedback').className='assembly-feedback error';}else acceptAssembly(result);}});montage.addEventListener('cancel',e=>{e.preventDefault();closeAssembly();});
function fuelAccessoriesArt(){if(!state.assembled.f)return '';const a=parts.find(p=>p.id==='fa'),c=parts.find(p=>p.id==='fc'),right=c.x>a.x,edge=c.x+(right?50:0),out=edge+(right?30:-30);return `<g aria-label="Seitliche Gaszuführungen, oberer Stromkreis und Wasserauslass"><path d="M${a.x+(a.x===664?-8:58)} 370H${a.x+(a.x===664?0:50)} M${c.x+(c.x===664?-8:58)} 370H${c.x+(c.x===664?0:50)}" stroke="#82aec4" stroke-width="5" fill="none"/>${txt(a.x+(a.x===664?-22:72),354,'H₂',14,'#187eae')}${txt(c.x+(c.x===664?-22:72),354,'O₂',14,'#ac5b4b')}<path d="M${edge} 430H${out}" stroke="#78aec8" stroke-width="5"/>${txt(out+(right?6:-6),449,`H₂O: ${state.product.toFixed(2).replace('.',',')} mL`,12,'#42748e',right?'start':'end')}</g>`;}
