'use strict';
const baseBench=renderBench;
const hofDialog=document.createElement('dialog');hofDialog.id='hofmannDialog';hofDialog.setAttribute('aria-labelledby','hofTitle');document.body.append(hofDialog);
let hofDrag=null;
const hofDraft=()=>state.drafts.e||(state.drafts.e={electrodes:[{id:'A',x:100,y:400},{id:'B',x:730,y:400}]});
function hofGlass(x,y,scale=1){const h=state.hof;const t=(x,y,text,size=14,color='#173248')=>txt(x,y,text,size/scale,color);const valve=(i,cx)=>`<g data-valve="${i}" tabindex="0" role="button" aria-label="Hahn ${i===0?'links':'rechts'} ${h.valves[i]?'schließen':'öffnen'}" class="valve"><rect x="${cx-28}" y="50" width="56" height="110" fill="transparent"/><circle cx="${cx}" cy="110" r="17" fill="#e2edf4" stroke="#738fa4"/><path d="${h.valves[i]?`M${cx} 92V128`:`M${cx-18} 110H${cx+18}`}" stroke="${h.valves[i]?'#168976':'#9c6244'}" stroke-width="7" stroke-linecap="round"/>${t(cx,78,h.valves[i]?'offen':'zu',15,'#4c6b7e')}</g>`;
const tube=(cx,i)=>{const level=h.filled?Math.max(.05,h.levels[i]-h.gas[i]/120*.8):0,lh=280*level;let ticks='';for(let j=1;j<=6;j++)ticks+=`<path d="M${cx+5} ${153+j*36}h12" stroke="#89acbf"/>`;return rect(cx-23,140,46,300,'#ffffff9c','#82aac3',12)+rect(cx-19,435-lh,38,lh,'#afddec','none',5)+ticks+t(cx,172,h.air[i]&&h.filled?'Luft':h.gas[i]>0?h.types[i]:'',13,'#4b7d95')+t(cx,475,`${h.gas[i].toFixed(1).replace('.',',')} mL`,16)+valve(i,cx);};
return `<g transform="translate(${x} ${y}) scale(${scale})"><path d="M320 423H520 M420 420V115" stroke="#82aac3" stroke-width="35" stroke-linejoin="round" fill="none"/><path d="M320 423H520 M420 420V115" stroke="#eef8fc" stroke-width="29" stroke-linejoin="round" fill="none"/>${h.filled?'<path d="M320 423H520 M420 423V180" stroke="#afddec" stroke-width="25" stroke-linejoin="round" fill="none"/>':''}${tube(320,0)}${tube(520,1)}${rect(388,110,64,92,'#edf8fdcc','#82aac3',9)}${h.filled?rect(392,196-(35+Math.min(22,(h.gas[0]+h.gas[1])*.1)),56,35+Math.min(22,(h.gas[0]+h.gas[1])*.1),'#afddec','none',6):''}${t(420,98,scale===1?'Vorratsrohr':'Vorrat',16)}${t(320,512,scale===1?'Gasauffangrohr':'Rohr A',14)}${t(520,512,scale===1?'Gasauffangrohr':'Rohr B',14)}<path d="M320 128V140 M520 128V140" stroke="#83a8bd" stroke-width="9"/>${state.assembled.e?`<path d="M320 452V395 M520 452V395" stroke="#6b7780" stroke-width="9"/>${rect(304,439,32,16,'#4d6172','none',3)}${rect(504,439,32,16,'#4d6172','none',3)}`:''}</g>`;}
function renderHofDialog(){const d=hofDraft();hofDialog.innerHTML=`<div class="montage-header"><div><p class="eyebrow">AUFBAU & BEFÜLLEN</p><h2 id="hofTitle">Hofmann’scher Wasserzersetzer</h2></div><button id="closeHof" class="quiet-button">Zur Gesamtanlage</button></div><p class="montage-instruction">Führe die beiden Elektroden unten in die Seitenrohre ein. Befülle den Apparat über das mittlere Vorratsrohr und untersuche die beiden Hähne.</p><div class="montage-scroll"><div id="hofArea"><svg viewBox="0 0 900 580" role="group" aria-label="Hofmann-Apparat mit mittlerem Vorratsrohr und zwei seitlichen Gasauffangrohren">${hofGlass(0,0)}</svg>${state.assembled.e?'':d.electrodes.map(p=>`<button class="hof-electrode" data-electrode="${p.id}" style="left:${p.x}px;top:${p.y}px" aria-label="Elektrode ${p.id}, mit Pfeiltasten verschieben"><span class="rod"></span><span class="plug"></span><span class="electrode-label">Elektrode ${p.id}</span></button>`).join('')}</div></div><div class="hof-controls"><label>Flüssigkeit <select id="fluid"><option value="">Auswählen</option><option value="water" ${state.hof.fluid==='water'?'selected':''}>Reines Wasser</option><option value="electrolyte" ${state.hof.fluid==='electrolyte'?'selected':''}>Wasser mit Elektrolyt</option></select></label><button id="fillHof" class="primary">Apparat befüllen</button><button id="mountHof" class="primary" ${state.assembled.e?'disabled':''}>Elektroden einsetzen</button><button id="clearHof" class="quiet-button">Apparat leeren</button><button id="takeElectrodes" class="quiet-button" ${state.assembled.e?'':'disabled'}>Elektroden herausnehmen</button></div><p id="hofFeedback" role="status" class="assembly-feedback">${state.assembled.e?'Die Elektroden sind eingesetzt. Die elektrischen Anschlüsse findest du in der Gesamtanlage.':'Verschiebe die Elektroden frei mit der Maus oder den Pfeiltasten.'}</p>`;}
function openHofmann(){state.running=false;state.producing=false;state.spinning=false;render();renderHofDialog();hofDialog.showModal();}
function hofFeedback(t){$('hofFeedback').textContent=t;}
function toggleValve(i){const h=state.hof;h.valves[i]=!h.valves[i];if(h.valves[i]&&h.filled&&h.air[i]){h.air[i]=false;h.levels[i]=1;}renderBench();if(hofDialog.open){renderHofDialog();hofFeedback(h.filled&&h.valves[i]?'Der Hahn ist geöffnet. Eingeschlossene Luft kann entweichen.':`Hahn ${i===0?'links':'rechts'} ${h.valves[i]?'geöffnet':'geschlossen'}.`);}else say(`Hahn ${i===0?'links':'rechts'} ${h.valves[i]?'geöffnet':'geschlossen'}.`);}
function fillHof(){const h=state.hof;if(!state.assembled.e){hofFeedback('Die Flüssigkeit läuft durch die offenen Rohrenden unten wieder heraus.');return;}if(!h.fluid){hofFeedback('Wähle eine Flüssigkeit zum Befüllen aus.');return;}if(h.gas.some(v=>v>.01)){hofFeedback('In den Seitenrohren befindet sich bereits Gas. Leere den Apparat vor einem neuen Befüllversuch.');return;}const wasFilled=h.filled;h.filled=true;state.water=100;for(let i=0;i<2;i++){const full=h.valves[i]||(wasFilled&&!h.air[i]);h.levels[i]=full?1:.18;h.air[i]=!full;}renderBench();renderHofDialog();hofFeedback(h.air.some(Boolean)?'Die Flüssigkeit steigt nur teilweise in den Seitenrohren. Über ihr bleibt eingeschlossene Luft.':'Die Flüssigkeit füllt beide Seitenrohre. Die zuvor enthaltene Luft ist entwichen.');}
function insertElectrodes(){const sorted=[...hofDraft().electrodes].sort((a,b)=>a.x-b.x);if(Math.abs(sorted[0].x+14-320)>18||Math.abs(sorted[1].x+14-520)>18||sorted.some(p=>Math.abs(p.y-383)>25)){hofFeedback('Die Elektroden schließen die beiden unteren Rohröffnungen noch nicht korrekt ab.');return;}state.assembled.e=true;state.placed.add('ec');state.placed.add('ea');renderHofDialog();render();hofFeedback('Beide Elektroden sitzen in den unteren Rohröffnungen. Befülle den Apparat und verbinde anschließend die Kabel.');}
function clearHof(){const h=state.hof;h.filled=false;h.levels=[0,0];h.air=[true,true];h.gas=[0,0];h.types=['',''];state.water=0;renderBench();renderHofDialog();hofFeedback('Der Apparat ist leer. Die Hahnstellungen bleiben erhalten.');}
function electricalPolarity(){if(has('sminus','eminus')&&has('splus','eplus'))return ['H₂','O₂'];if(has('splus','eminus')&&has('sminus','eplus'))return ['O₂','H₂'];return null;}
electroReady=function(){return state.assembled.e&&!!electricalPolarity()&&state.hof.filled&&!state.hof.air.some(Boolean)&&state.hof.fluid==='electrolyte';};
diagnose=function(){if(!state.assembled.e||!state.assembled.f)return 'Montiere zunächst beide Geräte.';if(!electricalPolarity())return 'Die Elektroden bilden mit der Solarzelle noch keinen geschlossenen Stromkreis.';if(!state.hof.filled)return 'Der Hofmann-Apparat ist leer.';if(state.hof.air.some(Boolean))return 'In einem Seitenrohr befindet sich noch eingeschlossene Luft. Untersuche den Befüllzustand.';if(state.hof.fluid!=='electrolyte')return 'Mit reinem Wasser ist keine nennenswerte Gasentwicklung sichtbar.';if(!electricalPolarity().every((g,i)=>has(i===0?'eh':'eo',g==='H₂'?'thin':'toin')))return 'Die Gaswege vom Hofmann-Apparat zu den Speichern sind noch nicht passend verbunden.';if(!gasReady()||!motorReady())return 'Gaszufuhr oder Motorstromkreis an der Brennstoffzelle sind noch nicht vollständig.';return null;};
renderBench=function(){for(const p of ports){if(p.id==='eminus')Object.assign(p,{x:306,y:460,color:'#526b7b',label:'Elektrode im linken Seitenrohr'});if(p.id==='eplus')Object.assign(p,{x:406,y:460,color:'#526b7b',label:'Elektrode im rechten Seitenrohr'});if(p.id==='eh')Object.assign(p,{x:306,y:209,label:'Linker Hahn · Gasausgang'});if(p.id==='eo')Object.assign(p,{x:406,y:209,label:'Rechter Hahn · Gasausgang'});}baseBench();const svg=$('bench').querySelector('svg');svg.querySelector('[data-device="e"]')?.remove();const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.innerHTML=`<path pointer-events="none" d="M306 209V229 M406 209V229" stroke="#82aac3" stroke-width="5"/>${state.assembled.e?'<path d="M306 411V460 M406 411V460" stroke="#526b7b" stroke-width="3"/>':''}${hofGlass(146,183,.5)}<g data-hof-open tabindex="0" role="button" aria-label="Hofmann-Apparat öffnen" class="slot">${rect(270,495,175,35,'#edf5fa','#adc7d8',7)}${txt(357,518,'Apparat öffnen',14)}</g>`;svg.append(g);svg.insertAdjacentHTML('beforeend',fuelAccessoriesArt());svg.querySelectorAll('.port').forEach(el=>svg.append(el));};
step=function(dt){if(dt>0)state.flowWires=new Set();const h=state.hof;state.power=state.light*Math.cos(state.angle*Math.PI/180);state.producing=state.running&&electroReady()&&state.power>.01&&h.gas.every(v=>v<105);const species=electricalPolarity();if(state.producing)for(let i=0;i<2;i++){const amount=(species[i]==='H₂'?4:2)*state.power/100*dt;if(h.types[i]&&h.types[i]!==species[i]&&h.gas[i]>.01)h.types[i]='Gemisch';else h.types[i]=species[i];h.gas[i]=Math.min(105,h.gas[i]+amount);}
if(state.running)for(let i=0;i<2;i++){if(!h.valves[i])continue;const amount=Math.min(h.gas[i],10*dt),gas=h.types[i],out=i===0?'eh':'eo';let moved=amount;if(gas==='H₂'&&has(out,'thin')){moved=Math.min(amount,120-state.h2);state.h2+=moved;if(moved>0)trackFlow(out,'thin');}else if(gas==='O₂'&&has(out,'toin')){moved=Math.min(amount,60-state.o2);state.o2+=moved;if(moved>0)trackFlow(out,'toin');}else h.escaped+=amount;h.gas[i]-=moved;}
state.spinning=state.running&&state.motor&&gasReady()&&motorReady()&&state.h2>.002&&state.o2>.001;if(state.spinning){const used=Math.min(.65*dt,state.h2/2,state.o2);state.h2-=2*used;state.o2-=used;state.product+=used*.0015;if(used>0){trackFlow('thout','fh');trackFlow('toout','fo');for(const w of state.wires.filter(w=>w.some(id=>['fminus','fplus'].includes(id))&&w.some(id=>['mminus','mplus'].includes(id))))trackFlow(...w);}state.rotor=(state.rotor+(has('fminus','mplus')?-1:1)*dt*260)%360;}
if(state.running){let msg,tone='';if(!state.assembled.e)msg='Die Elektroden fehlen im Hofmann-Apparat.';else if(!h.filled)msg='Der Apparat ist leer. Es entstehen keine Gase.';else if(h.air.some(Boolean))msg='Eingeschlossene Luft verhindert einen geeigneten Befüllzustand. Untersuche den Apparat.';else if(h.fluid!=='electrolyte')msg='Mit reinem Wasser ist keine nennenswerte Gasentwicklung sichtbar.';else if(!species)msg='Der Stromkreis zwischen Solarzelle und Elektroden ist unterbrochen.';else if(state.spinning&&state.power<.01){msg='Der Motor nutzt gespeicherte Gase weiter. Ohne Licht entstehen keine neuen Gase.';tone='good';}else if(h.types.includes('Gemisch'))msg='Nach dem Umpolen enthält ein Seitenrohr ein Gasgemisch. Leere den Apparat für einen neuen Versuch.';else if(state.producing&&h.valves.some(Boolean))msg='Bei geöffneten Hähnen bleibt das Gas nicht im Seitenrohr: Es strömt in einen passend angeschlossenen Speicher oder entweicht.';else if(state.producing){msg='Gas sammelt sich über der Flüssigkeit in den geschlossenen Seitenrohren. Die Flüssigkeit wird verdrängt.';tone='good';}else if(h.gas.some(v=>v>=105))msg='Ein Seitenrohr ist fast mit Gas gefüllt. Die Gasproduktion pausiert.';else msg='Die Elektrolyse steht. Vorhandenes Gas kann über geöffnete Hähne abgegeben werden.';if(msg!==feedbackKey){say(msg,tone);feedbackKey=msg;}}updateReadouts();renderBench();};
function hofAction(e){if(e.type==='keydown'&&!['Enter',' '].includes(e.key))return;const valve=e.target.closest('[data-valve]');if(valve){if(e.type==='keydown')e.preventDefault();toggleValve(Number(valve.dataset.valve));return;}if(e.target.closest('[data-hof-open]'))openHofmann();}
$('bench').addEventListener('click',hofAction);$('bench').addEventListener('keydown',hofAction);
hofDialog.addEventListener('click',e=>{const v=e.target.closest('[data-valve]');if(v)toggleValve(Number(v.dataset.valve));if(e.target.id==='fillHof')fillHof();if(e.target.id==='mountHof')insertElectrodes();if(e.target.id==='clearHof')clearHof();if(e.target.id==='closeHof'){hofDialog.close();render();}if(e.target.id==='takeElectrodes'){clearHof();state.assembled.e=false;state.placed.delete('ec');state.placed.delete('ea');state.wires=state.wires.filter(w=>!w.some(id=>['eminus','eplus','eh','eo'].includes(id)));renderHofDialog();render();}});
hofDialog.addEventListener('change',e=>{if(e.target.id==='fluid')state.hof.fluid=e.target.value;});
hofDialog.addEventListener('pointerdown',e=>{const el=e.target.closest('[data-electrode]');if(!el)return;const r=$('hofArea').getBoundingClientRect(),p=hofDraft().electrodes.find(p=>p.id===el.dataset.electrode);hofDrag={id:p.id,dx:e.clientX-r.left-p.x,dy:e.clientY-r.top-p.y};el.setPointerCapture(e.pointerId);el.focus();e.preventDefault();});
function moveHofElectrode(p,x,y){p.x=Math.max(0,Math.min(850,x));p.y=Math.max(0,Math.min(460,y));const el=hofDialog.querySelector(`[data-electrode="${p.id}"]`);el.style.left=p.x+'px';el.style.top=p.y+'px';}
hofDialog.addEventListener('pointermove',e=>{if(!hofDrag)return;const r=$('hofArea').getBoundingClientRect(),p=hofDraft().electrodes.find(p=>p.id===hofDrag.id);moveHofElectrode(p,e.clientX-r.left-hofDrag.dx,e.clientY-r.top-hofDrag.dy);});hofDialog.addEventListener('pointerup',()=>hofDrag=null);hofDialog.addEventListener('pointercancel',()=>hofDrag=null);
hofDialog.addEventListener('keydown',e=>{if(e.target.closest('[data-valve]')){if(['Enter',' '].includes(e.key)){e.preventDefault();toggleValve(Number(e.target.closest('[data-valve]').dataset.valve));}return;}const el=e.target.closest('[data-electrode]');if(!el||!e.key.startsWith('Arrow'))return;e.preventDefault();const p=hofDraft().electrodes.find(p=>p.id===el.dataset.electrode),n=e.shiftKey?20:5;moveHofElectrode(p,p.x+(e.key==='ArrowRight'?n:e.key==='ArrowLeft'?-n:0),p.y+(e.key==='ArrowDown'?n:e.key==='ArrowUp'?-n:0));});
render();


